# Generated by Django 4.2.24 on 2025-09-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='advantages',
            field=models.JSONField(blank=True, default=list, help_text="Список преимуществ. Формат: [{'title': 'Заголовок', 'description': 'Описание'}]", null=True),
        ),
    ]
