# Generated by Django 5.2.5 on 2025-09-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_review_options_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.hall'),
        ),
        migrations.AddField(
            model_name='club',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
