# Generated by Django 5.2.5 on 2025-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_club_hall_club_video_url_hall_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='price_per_hour',
        ),
        migrations.AddField(
            model_name='club',
            name='age_groups',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='coach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='price_per_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='training_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
