# Generated by Django 5.2.5 on 2025-08-19 11:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('working_hours', models.JSONField(blank=True, default=dict, verbose_name='Часы работы')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Изображения')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео')),
                ('advantages', models.JSONField(blank=True, default=list, verbose_name='Преимущества')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('hall_type', models.CharField(blank=True, choices=[('indoor', 'Крытый'), ('outdoor', 'Открытый'), ('mixed', 'Смешанный')], max_length=50, verbose_name='Тип зала')),
                ('coating', models.CharField(blank=True, max_length=50, verbose_name='Покрытие')),
                ('inventory', models.CharField(blank=True, max_length=100, verbose_name='Инвентарь')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за час')),
                ('dressing_room', models.BooleanField(default=False, verbose_name='Раздевалка')),
                ('lighting', models.BooleanField(default=False, verbose_name='Освещение')),
                ('shower', models.BooleanField(default=False, verbose_name='Душ')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('coach', models.CharField(max_length=100, verbose_name='Тренер')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('training_schedule', models.JSONField(default=dict, verbose_name='Расписание тренировок')),
                ('age_groups', models.JSONField(default=list, verbose_name='Возрастные группы')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за месяц')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/', verbose_name='Логотип')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='main.hall')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.club')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.hall')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'constraints': [models.CheckConstraint(condition=models.Q(('hall__isnull', False), ('club__isnull', False), _connector='OR'), name='not_both_null')],
            },
        ),
    ]
